name: dmp_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  flutter_svg: ^0.7.0+1
  font_awesome_flutter: ^8.2.0
  fluro: ^1.3.7
  shared_preferences: ^0.4.3
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value: ^6.2.0
  source_gen: ^0.9.3
  build_runner: ^1.1.2
  built_value_generator: ^6.2.0


analyzer:
  strong-mode:
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    always_declare_return_types: warning
    always_specify_types: warning

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/graphics/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/Poppins-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400

        - asset: assets/fonts/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: assets/fonts/Poppins-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/Poppins-Black.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          style: italic
          weight: 800

        - asset: assets/fonts/Poppins-ExtraBold.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
